# -*- coding: utf-8 -*-
# Copyright 2019 GTICA C.A. - Ing Henry Vivas

{
    'name': 'WT CtMetals Customization',
    'version': '14.0.1.0.0',
    'category': 'sales',
    'author': 'Warlock Technologies Pvt Ltd.',
    'website': 'http://warlocktechnologies.com',
    'support': 'info@warlocktechnologies.com',
    'license': 'AGPL-3',
    'depends': ['sale_management', 'purchase', 'project', 'stock', 'base', 'wt_stock_picking_report'],
    'data': [
        'views/sale_order_view.xml',
        'security/ir.model.access.csv',
        'security/res_group.xml',
        'data/mail_data.xml',
        'report/report_menu.xml',
        'report/dms_report_view.xml',
        'views/assets.xml',
        'views/sale_portal_template.xml',
        'views/account_move_view.xml',
        'views/account_report.xml',
        'views/external_layout.xml',
        'views/project.xml',
        'views/purchase_order_view.xml',
        'views/purchase_report.xml',
        'views/res_company_view.xml',
        'views/res_partner_view.xml',
        'views/sales_report.xml',
        'views/stock_picking_view.xml',
        'views/stock_report.xml',
        'views/reverse_charge_hmrc.xml',
        'views/delivery_portal.xml',
    ],
    'images': ['static/description/main_screenshot.png'],
    "qweb": ["static/src/xml/wt_signature.xml"],
    'application': False,
    'installable': True,
}
